name: Build ParCool Mod

on:
  pull_request:
  # Run on all pull requests regardless of target branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  detect-java:
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.get-java-version.outputs.java-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Java version from build.gradle
        id: get-java-version
        run: |
          # Extract Java version directly from build.gradle using grep and sed
          JAVA_VERSION=$(grep -o "JavaLanguageVersion.of([0-9]\+)" build.gradle | sed -E 's/JavaLanguageVersion.of\(([0-9]+)\)/\1/g' | head -1)
          
          # If no version found, default to Java 8
          if [ -z "$JAVA_VERSION" ]; then
            JAVA_VERSION=8
          fi
          
          echo "java-version=$JAVA_VERSION" >> $GITHUB_OUTPUT
          echo "Detected Java Version: $JAVA_VERSION"

  build:
    needs: detect-java
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ needs.detect-java.outputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ needs.detect-java.outputs.java-version }}
          distribution: 'temurin'  # Use Adoptium's Temurin distribution
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Build with Gradle
        run: ./gradlew build